# Generated by Django 6.0.7 on 2026-08-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('commented', 'Commented'), ('completed', 'Completed'), ('edited', 'Edited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='wishes.wish'),
        ),
    ]
