# Generated by Django 6.0.7 on 2026-09-02 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('date_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('First Date', 'First Date'), ('First Meeting', 'First Meeting'), ('Trip', 'Trip'), ('Achievement', 'Achievement'), ('Other', 'Other')], default='Other', max_length=30)),
                ('icon', models.CharField(default='❤️', max_length=50)),
                ('repeat_yearly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
