# Generated by Django 6.0.7 on 2026-09-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('promise_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Kept', 'Kept'), ('Broken', 'Broken')], default='Active', max_length=20)),
                ('kept_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
